# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      rust-bootstrap:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      node-bootstrap:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
