{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "filebelt.validate" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebelt.filebeltConfigName" . }}
  labels:
{{ include "filebelt.labels" . | indent 4 }}
  annotations:
    filebelt.dev/config-digest: {{ include "filebelt.renderedFilebeltConfiguration" . | sha256sum | quote }}
immutable: true
data:
  filebelt.toml: |
{{ include "filebelt.renderedFilebeltConfiguration" . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebelt.oxibeltConfigName" . }}
  labels:
{{ include "filebelt.labels" . | indent 4 }}
  annotations:
    filebelt.dev/config-digest: {{ tpl .Values.configuration.oxibelt . | sha256sum | quote }}
immutable: true
data:
  oxibelt.toml: |
{{ tpl .Values.configuration.oxibelt . | indent 4 }}
