{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $root := . -}}
{{- range $component := list "web" "api" "io" "maintenance" "tools" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filebelt.name" $root }}-{{ $component }}
  labels:
{{ include "filebelt.componentLabels" (dict "root" $root "component" $component) | indent 4 }}
automountServiceAccountToken: false
---
{{- end }}
