// SPDX-License-Identifier: Apache-2.0

export const en = {
  account: "Account",
  activeSession: "Current session",
  admin: "Administration",
  allFiles: "All files",
  anonymousLink: "Anonymous link",
  appName: "FileBelt",
  close: "Close",
  compact: "Compact",
  comfortable: "Comfortable",
  conflict: "Conflict",
  contributor: "Contributor",
  copyLink: "Copy link",
  createdGroup: (name: string): string => `Created group ${name}`,
  createdSharedDrive: (name: string): string => `Created shared drive ${name}`,
  current: "Current",
  createShare: "Create share",
  dark: "Dark",
  details: "Details",
  directShare: "Person",
  deselectItem: (name: string): string => `Deselect ${name}`,
  downloadStarted: (name: string): string => `Download started for ${name}`,
  download: "Download",
  file: "File",
  fileCommands: "File commands",
  files: "Files",
  folder: "Folder",
  groupShare: "Group",
  itemsRestored: "Items restored",
  itemsTrashed: "Items moved to Trash",
  linkSecurity: "Links are read-only and expire in seven days by default.",
  light: "Light",
  loading: "Loading your files",
  mainNavigation: "FileBelt navigation",
  manager: "Manager",
  markRead: "Mark all read",
  modified: "Modified",
  moreActions: "More actions",
  moveToTrash: "Move to Trash",
  myDrive: "My Drive",
  name: "Name",
  newFolder: "New folder",
  noFiles: "Nothing is here yet",
  noPrivacyEvents: "No privacy events in the last 90 days.",
  noShares: "This item has no active shares.",
  noVersions: "Select a file to inspect its version history.",
  noSelection: "Select an item to see details.",
  offline: "The service could not be reached. Your files were not changed.",
  openMenu: "Open selection actions",
  selectionActions: "Selection actions",
  owner: "Owner",
  privacy: "Privacy",
  privacyDescription: "Security-sensitive administrative actions involving your account appear here for 90 days.",
  privacyRead: "Privacy events marked as read",
  publicDownload: "Download shared file",
  publicExpired: "This link is invalid, revoked, or expired.",
  publicLoading: "Opening secure share",
  publicShare: "Shared with you",
  publicShareNotice: "This isolated page cannot access your FileBelt account session.",
  progress: "Progress",
  quarantined: "Quarantined",
  ready: "Ready",
  recent: "Recent",
  refresh: "Refresh",
  restore: "Restore",
  restoreVersion: "Restore as new version",
  revoke: "Revoke",
  saveShare: "Share",
  search: "Search files",
  signIn: "Sign in",
  signInDescription: "Your FileBelt session is missing or has expired. Sign in again to continue.",
  signInRequired: "Sign in to FileBelt",
  selected: "selected",
  selectedAnnouncement: (count: number): string => `${count} ${count === 1 ? "item" : "items"} selected`,
  selectItem: (name: string): string => `Select ${name}`,
  sessions: "Sessions",
  sessionsDescription: "Review where your FileBelt account is signed in and revoke devices you no longer use.",
  sessionRevoked: "Session revoked",
  shareKind: "Share type",
  sharePermission: "Permission",
  shareTarget: "Verified email or group name",
  shared: "Shared with me",
  sharedDrives: "Shared drives",
  shares: "Shares",
  shareCreated: "Share created",
  shareRevoked: "Share revoked",
  size: "Size",
  status: "Status",
  skipToContent: "Skip to content",
  system: "System",
  theme: "Theme",
  trash: "Trash",
  upload: "Upload",
  uploadCompleted: (count: number): string => `${count} ${count === 1 ? "upload" : "uploads"} completed`,
  uploadPrivacy: "Uploads remain resumable without storing account or capability tokens in this browser.",
  userStatusUpdated: "Updated account status",
  uploading: "Uploading",
  uploadHint: "Upload files to My Drive",
  uploads: "Uploads",
  userMenu: "Account and appearance",
  version: "Version",
  versionCreated: "Created",
  versionCreator: "Created by",
  versionRestored: "Restored content as a new version",
  permissionDenied: "You do not have permission to administer this tenant.",
  versions: "Versions",
  viewer: "Viewer",
  viewSettings: "Appearance",
  working: "Working…",
} as const;

export type Strings = typeof en;
