// SPDX-License-Identifier: Apache-2.0

export const En = {
  account: "Account",
  activeSession: "Current session",
  admin: "Administration",
  allFiles: "All files",
  anonymousLink: "Anonymous link",
  appName: "FileBelt",
  backToFiles: "Back to files",
  close: "Close",
  compact: "Compact",
  comfortable: "Comfortable",
  conflict: "Conflict",
  contributor: "Contributor",
  copyLink: "Copy link",
  createdGroup: (Name: string): string => `Created group ${Name}`,
  createdSharedDrive: (Name: string): string => `Created shared drive ${Name}`,
  current: "Current",
  createShare: "Create share",
  dark: "Dark",
  details: "Details",
  directShare: "Person",
  deselectItem: (Name: string): string => `Deselect ${Name}`,
  downloadStarted: (Name: string): string => `Download started for ${Name}`,
  download: "Download",
  file: "File",
  fileCommands: "File commands",
  files: "Files",
  folder: "Folder",
  groupShare: "Group",
  itemsRestored: "Items restored",
  itemsTrashed: "Items moved to Trash",
  linkSecurity: "Links are read-only and expire in seven days by default.",
  light: "Light",
  loading: "Loading your files",
  mainNavigation: "FileBelt navigation",
  markdown: "Markdown",
  markdownConflict: "This file changed on the server. Your local edits are still available; reload before saving again.",
  markdownExportLocal: "Export local copy",
  markdownDiscardChanges: "Discard changes",
  markdownLeaveDescription: "You have unsaved Markdown changes. Export a local copy before leaving, discard them, or stay and continue editing.",
  markdownLeaveHeading: "Leave without saving?",
  markdownStay: "Stay",
  markdownConflictCopySaved: "Saved the local edits as a new sibling file.",
  markdownConflictMerged: "The latest version was merged with your local edits. Review and save the result.",
  markdownConflictReview: "Both versions changed the same lines. Resolve the marked sections, then save or keep a conflict copy.",
  markdownCollaborationConnected: "Live collaboration connected.",
  markdownCollaborationConnecting: "Connecting live collaboration…",
  markdownCollaborationDisconnected: "Live collaboration disconnected. Reconnect to continue editing.",
  markdownLoading: "Loading Markdown file",
  markdownMcpCapability: "Approved capability",
  markdownMcpConfirm: "Confirm this exact MCP proposal request. It cannot save your file.",
  markdownMcpConfirmButton: "Confirm proposal",
  markdownMcpHeading: "MCP proposal",
  markdownMcpNotice: "The current Markdown source and selected range are sent only after confirmation. Results remain proposals until you apply them.",
  markdownMcpPropose: "Request proposal",
  markdownMcpSelect: "Select an option",
  markdownMcpServer: "MCP server",
  markdownMcpUnavailable: "MCP proposals are unavailable.",
  markdownProposalApply: "Apply proposal to current source",
  markdownProposalPreview: "Markdown proposal",
  markdownProposalStale: "The source changed while this proposal was running. Review it and request a new proposal.",
  markdownReconnect: "Reconnect",
  markdownReferenceUnavailable: "This FileBelt item is not available in the current workspace.",
  markdownSaveFailed: "Markdown could not be saved. Your local edits are still available.",
  markdownSaveConflictCopy: "Save local edits as a copy",
  markdownUnavailable: "This file cannot be opened as Markdown.",
  markdownSelection: (Start: number, End: number): string => `Selected source range: ${Start}–${End}`,
  manager: "Manager",
  mcp: "MCP servers",
  mounts: "Mounted access",
  markRead: "Mark all read",
  modified: "Modified",
  moreActions: "More actions",
  moveToTrash: "Move to Trash",
  myDrive: "My Drive",
  name: "Name",
  newFolder: "New folder",
  noFiles: "Nothing is here yet",
  noPrivacyEvents: "No privacy events in the last 90 days.",
  noShares: "This item has no active shares.",
  noVersions: "Select a file to inspect its version history.",
  noSelection: "Select an item to see details.",
  offline: "The service could not be reached. Your files were not changed.",
  openMenu: "Open selection actions",
  openMarkdown: "Open Markdown",
  importMarkdown: "Import as Markdown",
  markdownImportCompleted: (Name: string): string => `Imported ${Name} as a new Markdown file`,
  markdownImportUnavailable: "This Office file cannot be imported safely in the browser.",
  selectionActions: "Selection actions",
  owner: "Owner",
  privacy: "Privacy",
  privacyDescription: "Security-sensitive administrative actions involving your account appear here for 90 days.",
  privacyRead: "Privacy events marked as read",
  publicDownload: "Download shared file",
  publicExpired: "This link is invalid, revoked, or expired.",
  publicLoading: "Opening secure share",
  publicShare: "Shared with you",
  publicShareNotice: "This isolated page cannot access your FileBelt account session.",
  progress: "Progress",
  quarantined: "Quarantined",
  ready: "Ready",
  recent: "Recent",
  refresh: "Refresh",
  restore: "Restore",
  restoreVersion: "Restore as new version",
  revoke: "Revoke",
  saveShare: "Share",
  search: "Search files",
  save: "Save",
  signIn: "Sign in",
  signInDescription: "Your FileBelt session is missing or has expired. Sign in again to continue.",
  signInRequired: "Sign in to FileBelt",
  selected: "selected",
  selectedAnnouncement: (Count: number): string => `${Count} ${Count === 1 ? "item" : "items"} selected`,
  selectItem: (Name: string): string => `Select ${Name}`,
  sessions: "Sessions",
  sessionsDescription: "Review where your FileBelt account is signed in and revoke devices you no longer use.",
  sessionRevoked: "Session revoked",
  shareKind: "Share type",
  sharePermission: "Permission",
  shareTarget: "Verified email or group name",
  shared: "Shared with me",
  sharedDrives: "Shared drives",
  shares: "Shares",
  shareCreated: "Share created",
  shareRevoked: "Share revoked",
  size: "Size",
  status: "Status",
  skipToContent: "Skip to content",
  system: "System",
  theme: "Theme",
  trash: "Trash",
  upload: "Upload",
  uploadCompleted: (Count: number): string => `${Count} ${Count === 1 ? "upload" : "uploads"} completed`,
  uploadPrivacy: "Uploads remain resumable without storing account or capability tokens in this browser.",
  userStatusUpdated: "Updated account status",
  uploading: "Uploading",
  uploadHint: "Upload files to My Drive",
  uploads: "Uploads",
  userMenu: "Account and appearance",
  version: "Version",
  versionCreated: "Created",
  versionCreator: "Created by",
  versionRestored: "Restored content as a new version",
  permissionDenied: "You do not have permission to administer this tenant.",
  versions: "Versions",
  viewer: "Viewer",
  viewSettings: "Appearance",
  working: "Working…",
} as const;

export type Strings = typeof En;
