# SPDX-License-Identifier: Apache-2.0

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(FILEBELT_RISCV64_TOOLCHAIN_PREFIX
    "/x-tools/riscv64-unknown-linux-musl/bin/riscv64-unknown-linux-musl-")
set(FILEBELT_RISCV64_SYSROOT
    "/x-tools/riscv64-unknown-linux-musl/riscv64-unknown-linux-musl/sysroot")

set(CMAKE_C_COMPILER "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_ASM_COMPILER "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}g++")
set(CMAKE_AR "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}ar")
set(CMAKE_LINKER "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}ld")
set(CMAKE_NM "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}nm")
set(CMAKE_OBJCOPY "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}objcopy")
set(CMAKE_OBJDUMP "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}objdump")
set(CMAKE_RANLIB "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}ranlib")
set(CMAKE_STRIP "${FILEBELT_RISCV64_TOOLCHAIN_PREFIX}strip")

set(CMAKE_SYSROOT "${FILEBELT_RISCV64_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${FILEBELT_RISCV64_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(FILEBELT_RISCV64_OBJECT_FLAGS
    "-ffunction-sections -fdata-sections -fPIC -march=rv64gc -mabi=lp64d -mcmodel=medany")
set(CMAKE_C_FLAGS_INIT "${FILEBELT_RISCV64_OBJECT_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${FILEBELT_RISCV64_OBJECT_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT "${FILEBELT_RISCV64_OBJECT_FLAGS}")
