#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""Generate the deterministic TypeScript client schema for the FileBelt UI."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


GENERATOR = "openapi-typescript"
GENERATOR_VERSION = "7.13.0"
SOURCE = Path("protocol/http/v1/openapi.yaml")
OUTPUT = Path("ui/web/source/generated/openapi.ts")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, required=True)
    args = parser.parse_args()
    root = args.repo_root.resolve()

    package = json.loads((root / "ui/web/package.json").read_text(encoding="utf-8"))
    actual_version = package.get("devDependencies", {}).get(GENERATOR)
    if actual_version != GENERATOR_VERSION:
        raise RuntimeError(
            f"ui/web/package.json must pin {GENERATOR}@{GENERATOR_VERSION}, "
            f"found {actual_version!r}"
        )

    output = root / OUTPUT
    output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "pnpm",
            "--filter",
            "@filebelt/web",
            "exec",
            GENERATOR,
            str(root / SOURCE),
            "--output",
            str(output),
            "--immutable",
            "--alphabetize",
        ],
        cwd=root,
        check=True,
    )
    generated = output.read_text(encoding="utf-8")
    if "This file was auto-generated by openapi-typescript" not in generated[:500]:
        raise RuntimeError(f"unexpected {GENERATOR} output header: {output}")
    metadata = (
        "// SPDX-FileCopyrightText: 2026 PiQuark6046 and FileBelt contributors\n"
        "// SPDX-License-Identifier: Apache-2.0\n"
        "//\n"
        f"// Source: {SOURCE.as_posix()}\n"
        f"// Generator: {GENERATOR}@{GENERATOR_VERSION}\n"
        "// Regenerate: python3 protocol/generate-openapi-client.py --repo-root .\n"
    )
    output.write_text(metadata + generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
