// SPDX-License-Identifier: Apache-2.0

export const McpEn = {
  activity: "Activity",
  add: "Add server",
  administration: "Managed MCP",
  adminNotice:
    "Sensitive changes require recent sign-in. Administration does not grant access to user credentials, arguments, results, filenames, or content.",
  apiKey: "API key",
  argumentsInvalid: "Arguments must be valid JSON.",
  application: "Application",
  applicationId: "Application ID",
  approve: "Approve",
  approveOnce: "Approve once and run",
  approvedCapability: "Approved capability",
  assignTemplate: "Assign template",
  authentication: "Authentication",
  attachments: "Attachments",
  bearer: "Bearer token",
  block: "Block",
  blockOrigin: "Block origin",
  cancel: "Cancel",
  cancelInvocation: "Cancel invocation",
  capabilities: "Capabilities",
  capability: "Capability",
  capabilityOption: (Title: string, Kind: string, Name: string): string =>
    `${Title} (${Kind}: ${Name})`,
  capabilityChanged:
    "Capabilities changed. Review new or changed entries before enabling this server.",
  capabilityFingerprint: "Exact capability fingerprint",
  capabilityKind: "Capability kind",
  capabilityName: "Exact capability name",
  connectOauth: "Connect with OAuth",
  confirmInvocation: "Confirm exact invocation",
  confirmInvocationNotice:
    "FileBelt will approve only this exact server, capability, application, arguments, and attachment set. The approval is consumed by this invocation.",
  credentialNotice:
    "Credentials are sent once to FileBelt and are never displayed or stored by this browser.",
  credentialState: "Current credential state",
  credentialType: "Credential type",
  createGrant: "Create 24-hour grant",
  createService: "Create service",
  createTemplate: "Create template",
  delete: "Delete",
  description:
    "Connect reviewed read-only MCP servers and control exactly what each invocation may receive.",
  displayName: "Display name",
  disable: "Disable",
  disabled: "Disabled",
  discover: "Discover capabilities",
  empty: "No MCP servers are configured.",
  enable: "Enable",
  enabled: "Enabled",
  endpoint: "HTTPS endpoint",
  endpointHint: "https://mcp.example.test/mcp",
  error: "The MCP request could not be completed.",
  export: "Export configuration",
  exactOrigin: "Exact origin",
  exactPrincipalId: "Exact principal ID",
  exactSpiffeUri: "Exact SPIFFE URI",
  invoke: "Run test invocation",
  import: "Import configuration",
  importDocument: "Non-secret FileBelt MCP registration JSON",
  intentExpires: "Intent expires",
  invocationRunning: "The MCP invocation is running.",
  invocationProgress: "MCP invocation progress",
  jsonArguments: "JSON arguments",
  jsonResult: "JSON result",
  managed: "Managed",
  managedLocked:
    "Endpoint and trust settings are managed by your administrator. Your credentials and approvals remain private.",
  managedTemplateUnavailable: "Managed template is unavailable.",
  managedTemplate: "Managed template",
  managedTemplates: "Managed templates",
  name: "Server name",
  noActivity: "No MCP activity in the last 90 days.",
  noCapabilities: "Discover this server before reviewing capabilities.",
  none: "None",
  oauthNotice:
    "OAuth opens the authorization server in this tab. FileBelt stores the pending state on the server.",
  resultAudioUnavailable: "Audio playback is unavailable.",
  resultImageAlt: "MCP server result",
  resultUnsupported: "Unsupported value",
  resultTruncated: "Result truncated at the safe display limit.",
  personal: "Personal",
  refresh: "Refresh",
  registrationHeading: "MCP servers",
  registration: "Registration",
  registrationList: "MCP registration list",
  results: "Invocation result",
  revoke: "Revoke credentials",
  review: "Save review",
  secret: "Credential value",
  selectRegistration: "Select a registration",
  selectService: "Select a service",
  selectTemplate: "Select a template",
  server: "Server",
  serverTested: "Connection test completed.",
  service: "Service",
  serviceGrantNotice:
    "Creates a 24-hour exact grant. Data grants must already be assigned to the service.",
  serviceGrants: "Service invocation grants",
  serviceIdentities: "Service identities",
  serviceUnavailable: "Service identity is unavailable.",
  saveCredential: "Save credential",
  status: "Status",
  templateAssignments: "Template assignments",
  principalKind: "Principal kind",
  originBlocks: "Global origin blocks",
  group: "Group",
  prompt: "Prompt",
  resource: "Resource",
  tool: "Tool",
  user: "User",
  assignmentCount: (Count: number): string =>
    `${Count} ${Count === 1 ? "assignment" : "assignments"}`,
  test: "Test connection",
  trustProfile: "Trust profile",
  unsafeMedia: "Media was rejected because its type or size is not supported.",
  working: "Working…",
} as const;
