{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "filebelt-git.validate" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filebelt-git.name" . }}
  labels:
{{ include "filebelt-git.labels" . | indent 4 }}
  annotations:
{{ include "filebelt-git.annotations" . | indent 4 }}
automountServiceAccountToken: false
