// SPDX-License-Identifier: Apache-2.0

export const AdminEn = {
  active: "Active",
  create: "Create",
  createGroup: "Create group",
  createSharedDrive: "Create shared drive",
  driveName: "Shared drive name",
  drives: "Shared drives",
  groups: "Groups",
  heading: "Tenant administration",
  managerCount: "Managers",
  memberCount: "Members",
  nfs: "NFS",
  nfsAdministration: "NFS administration",
  nfsAllowedExports: "Allowed exports",
  nfsApplied: "Applied",
  nfsAppliedGateway: "Applied gateway",
  nfsAppliedGeneration: "Applied generation",
  nfsAppliedManifestGeneration: "Applied manifest generation",
  nfsAppliedState: "Applied state",
  nfsCreateMapping: "Create mapping",
  nfsConfirmExportTransition: "I reviewed this export’s desired and applied state and want to stage a drain or disable transition.",
  nfsConfirmFeatureTransition: "I reviewed the manifest generations and want to activate, drain, or disable NFS.",
  nfsConfirmMappingChange: "I confirm this complete principal mapping and allowed-export selection.",
  nfsConfirmMappingRevoke: "I confirm this mapping should be revoked.",
  nfsDesiredGeneration: "Desired generation",
  nfsDesiredManifestGeneration: "Desired manifest generation",
  nfsDesiredState: "Desired state",
  nfsDriveId: "Drive ID",
  nfsEpoch: "epoch",
  nfsExactRealmHelp: "Map one exact RPCSEC_GSS user principal. The API rejects aliases, service principals, root, and any realm other than the deployment’s configured realm.",
  nfsExpectedGeneration: "Expected generation for update (leave blank to create)",
  nfsExportId: "Export ID",
  nfsExportRegistered: "NFS export registered in the disabled desired state.",
  nfsExportTransitioned: "NFS export desired state staged.",
  nfsExports: "Exports",
  nfsExportsHelp: "Desired state is operator intent. Applied state is the gateway’s reconciled generation; pending rows are not ready for traffic.",
  nfsFeature: "Feature state",
  nfsFeatureGeneration: "Feature generation",
  nfsFeatureHelp: "Transitions are generation-fenced. Activation begins with preflight; shutdown drains before disabling.",
  nfsFeatureTransitioned: "NFS feature state advanced.",
  nfsGeneration: "Generation",
  nfsGroupId: "FileBelt group ID",
  nfsGroupRegistered: "NFS POSIX group projection registered.",
  nfsGroupsHelp: "Numeric IDs are compatibility projections only and never grant FileBelt authority.",
  nfsKerberosPrincipal: "Kerberos principal in the exact configured realm",
  nfsKerberosPrincipalHelp: "Enter the complete case-sensitive value, for example user@CONFIGURED.REALM. The configured realm is never inferred by the browser.",
  nfsLoading: "Loading NFS administration",
  nfsManifestApplied: "Manifest applied",
  nfsManifestPending: "Manifest pending",
  nfsMapPrincipal: "Register or update principal mapping",
  nfsMappingRevoked: "NFS principal mapping revoked and active sessions closed.",
  nfsMappingSaved: "NFS principal mapping saved and active sessions fenced.",
  nfsMappingUpdateHelp: "Updates require the current generation and the complete allowed-export selection. Mapping changes close affected NFS sessions.",
  nfsMappings: "Exact principal mappings",
  nfsMappingsHelp: "Kerberos and numeric POSIX values resolve one FileBelt user but do not replace Virtual ACL authorization.",
  nfsMutationFailed: "The NFS administration change was not applied.",
  nfsNetworkStorage: "Network storage",
  nfsNoExportTransition: "No safe transition is currently available.",
  nfsNoExports: "No NFS exports are registered.",
  nfsNoExportsForMapping: "Register an export before creating a mapping.",
  nfsNoMappings: "No active NFS principal mappings are registered.",
  nfsNoPosixGroups: "No POSIX group projections are registered.",
  nfsPending: "Pending",
  nfsPosixGroups: "POSIX group projections",
  nfsPosixName: "POSIX name",
  nfsPrincipalId: "FileBelt user principal ID",
  nfsProjectedGid: "Projected GID",
  nfsProjectedUid: "Projected UID",
  nfsReauthenticationRequired: "NFS administration requires a recent tenant administrator sign-in.",
  nfsRevokeMappingHelp: "Revocation immediately removes the mapping, disables its NFS policy, and closes active NFS sessions. The current generation remains the server precondition.",
  nfsRegisterExport: "Register export",
  nfsRegisterExportHelp: "Registration creates a disabled desired row. Use the staged controls below to make it active.",
  nfsRegisterGroupHelp: "Register an existing FileBelt group before assigning its projected GID to a user mapping.",
  nfsRegisterPosixGroup: "Register POSIX group",
  nfsRestoreGeneration: "Restore generation",
  nfsSafetyNotice: "PostgreSQL is authoritative. Desired and applied generations remain visible so pending gateway reconciliation cannot look active.",
  nfsTransitionTo: (State: string) => `Transition to ${State}`,
  nfsUnavailable: "NFS administration is unavailable.",
  nfsUpdateMapping: "Update mapping",
  none: "None",
  register: "Register",
  quota: "Quota",
  reauth: "Sensitive changes require recent sign-in and are recorded in the affected user’s Privacy view.",
  resume: "Resume",
  status: "Status",
  signInAgain: "Sign in again",
  suspend: "Suspend",
  suspended: "Suspended",
  usage: "Storage use",
  users: "Users",
  revoke: "Revoke",
  tryAgain: "Try again",
} as const;
