// SPDX-License-Identifier: Apache-2.0

export const AdminEn = {
  active: "Active",
  create: "Create",
  createGroup: "Create group",
  createSharedDrive: "Create shared drive",
  driveName: "Shared drive name",
  drives: "Shared drives",
  groups: "Groups",
  heading: "Tenant administration",
  managerCount: "Managers",
  memberCount: "Members",
  nfs: "NFS",
  nfsAdministration: "NFS administration",
  nfsAllowedExports: "Allowed exports",
  nfsAllowedExportsUnknown: "Unknown in this legacy replay response",
  nfsAttenuateScope: "Reduce allowed exports",
  nfsApplied: "Applied",
  nfsAppliedGateway: "Applied gateway",
  nfsAppliedGeneration: "Applied generation",
  nfsAppliedManifestGeneration: "Applied manifest generation",
  nfsAppliedState: "Applied state",
  nfsCancelProposalHelp: "Cancel this exact pending proposal before submitting changed identity or scope fields.",
  nfsConfirmProposal: "I confirm this exact proposal and understand the target user must approve it after a recent sign-in.",
  nfsConfirmProposalCancel: "I confirm this pending proposal should be cancelled.",
  nfsConfirmExportTransition: "I reviewed this export’s desired and applied state and want to stage a drain or disable transition.",
  nfsConfirmFeatureTransition: "I reviewed the manifest generations and want to activate, drain, or disable NFS.",
  nfsConfirmConflictDiscard: "I confirm this retained conflict should be discarded.",
  nfsConfirmMappingRevoke: "I confirm this mapping should be revoked.",
  nfsConfiguredRealm: "Configured Kerberos realm",
  nfsCreateProposal: "Send approval proposal",
  nfsConflict: "Retained NFS write conflict",
  nfsConflictCopied: "The retained NFS write conflict was copied to a new file.",
  nfsConflictCopyHelp: "Choose an authorized parent in the conflict’s drive, a new display name, and the exact current parent generation.",
  nfsConflictCopyName: "New file display name",
  nfsConflictDiscarded: "The retained NFS write conflict was discarded.",
  nfsConflictExpires: "Expires",
  nfsConflicts: "Retained write conflicts",
  nfsConflictsHelp: "Conflict bytes remain isolated until you copy them into an authorized directory or explicitly discard them.",
  nfsCopyConflict: "Copy conflict",
  nfsDesiredGeneration: "Desired generation",
  nfsDesiredManifestGeneration: "Desired manifest generation",
  nfsDesiredState: "Desired state",
  nfsDriveId: "Drive ID",
  nfsEpoch: "epoch",
  nfsExactRealmHelp: "Map one exact RPCSEC_GSS user principal. Multiple aliases for one user must share one POSIX identity. The API rejects service principals, root, and any realm other than the deployment’s configured realm.",
  nfsExpectedParentGeneration: "Expected parent generation",
  nfsExportId: "Export ID",
  nfsExportRegistered: "NFS export registered in the disabled desired state.",
  nfsExportTransitioned: "NFS export desired state staged.",
  nfsExports: "Exports",
  nfsExportsHelp: "Desired state is operator intent. Applied state is the gateway’s reconciled generation; pending rows are not ready for traffic.",
  nfsFeature: "Feature state",
  nfsFeatureGeneration: "Feature generation",
  nfsFeatureHelp: "Transitions are generation-fenced. Activation begins with preflight; shutdown drains before disabling.",
  nfsFeatureTransitioned: "NFS feature state advanced.",
  nfsGeneration: "Generation",
  nfsGroupId: "FileBelt group ID",
  nfsGroupRegistered: "NFS POSIX group projection registered.",
  nfsGroupsHelp: "Numeric IDs are compatibility projections only and never grant FileBelt authority.",
  nfsKerberosPrincipal: "Kerberos principal in the exact configured realm",
  nfsKerberosPrincipalHelp: "Enter the complete case-sensitive value, for example user@CONFIGURED.REALM. The configured realm is never inferred by the browser.",
  nfsLoading: "Loading NFS administration",
  nfsLogicalSize: "Logical size in bytes",
  nfsManifestApplied: "Manifest applied",
  nfsManifestPending: "Manifest pending",
  nfsMappingAttenuated: "NFS mapping scope reduced and active sessions fenced.",
  nfsMappingRevoked: "NFS principal mapping revoked and active sessions closed.",
  nfsMappings: "Exact principal mappings",
  nfsMappingsHelp: "Only target-approved active mappings appear here. Scope can be reduced without reapproval; widening requires a new proposal.",
  nfsMutationFailed: "The NFS administration change was not applied.",
  nfsNetworkStorage: "Network storage",
  nfsNoExportTransition: "No safe transition is currently available.",
  nfsNoConflicts: "No retained NFS write conflicts require action.",
  nfsNoExports: "No NFS exports are registered.",
  nfsNoExportsForMapping: "Register an export before creating a mapping.",
  nfsNoMappings: "No active NFS principal mappings are registered.",
  nfsNoPendingProposals: "No NFS mapping proposals await target approval.",
  nfsNoPosixGroups: "No POSIX group projections are registered.",
  nfsNoQuarantinedMappings: "No legacy NFS mappings are quarantined.",
  nfsPending: "Pending",
  nfsPendingProposals: "Pending target approvals",
  nfsPendingProposalsHelp: "A proposal expires after 24 hours. Its target must recently sign in and approve the exact server-held fields.",
  nfsPosixGroups: "POSIX group projections",
  nfsPosixName: "POSIX name",
  nfsParentId: "Target parent ID",
  nfsPrincipalId: "FileBelt user principal ID",
  nfsProjectedGid: "Projected GID",
  nfsProjectedUid: "Projected UID",
  nfsProposalCancelled: "The pending NFS mapping proposal was cancelled.",
  nfsProposalCreatedAt: "Created",
  nfsProposalCreated: "The NFS mapping proposal is waiting for target approval.",
  nfsProposalExpires: "Expires",
  nfsProposalHelp: "Creating a proposal grants no NFS access. The target user must approve the exact Kerberos identity, POSIX projection, and drive ceiling.",
  nfsProposalId: "Proposal ID",
  nfsProposeMapping: "Propose principal mapping",
  nfsProposedBy: "Proposed by",
  nfsQuarantineReason: "Reason",
  nfsQuarantined: "Quarantined",
  nfsQuarantinedAt: "Quarantined",
  nfsQuarantinedMappings: "Quarantined legacy mappings",
  nfsQuarantinedMappingsHelp: "Legacy mappings cannot authenticate. Re-propose an exact mapping and obtain fresh target approval; quarantine is never grandfathered.",
  nfsReauthenticationRequired: "NFS administration requires a recent tenant administrator sign-in.",
  nfsRevokeMappingHelp: "Revocation immediately removes the mapping, disables its NFS policy, and closes active NFS sessions. The current generation remains the server precondition.",
  nfsRegisterExport: "Register export",
  nfsRegisterExportHelp: "Registration creates a disabled desired row. Use the staged controls below to make it active.",
  nfsRegisterGroupHelp: "Register an existing FileBelt group before assigning its projected GID to a user mapping.",
  nfsRegisterPosixGroup: "Register POSIX group",
  nfsRetained: "Retained",
  nfsRestoreGeneration: "Restore generation",
  nfsSafetyNotice: "PostgreSQL is authoritative. Desired and applied generations remain visible so pending gateway reconciliation cannot look active.",
  nfsSaveAttenuatedScope: "Save reduced scope",
  nfsSourceNodeId: "Source node ID",
  nfsTenantConfirmation: "Tenant confirmation",
  nfsTenantConfirmationHelp: "This value is compared exactly without trimming, normalization, or case folding. It is cleared after every mutation.",
  nfsTenantConfirmationLabel: (TenantSlug: string) => `Type ${TenantSlug} to enable one NFS mutation`,
  nfsDiscardConflict: "Discard conflict",
  nfsTransitionTo: (State: string) => `Transition to ${State}`,
  nfsUnavailable: "NFS administration is unavailable.",
  nfsUpdateMapping: "Update mapping",
  cancel: "Cancel",
  none: "None",
  register: "Register",
  quota: "Quota",
  reauth: "Sensitive changes require recent sign-in and are recorded in the affected user’s Privacy view.",
  resume: "Resume",
  status: "Status",
  signInAgain: "Sign in again",
  suspend: "Suspend",
  suspended: "Suspended",
  usage: "Storage use",
  users: "Users",
  revoke: "Revoke",
  tryAgain: "Try again",
} as const;
