# SPDX-License-Identifier: Apache-2.0

[package]
name = "filebelt-directory-repository-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
filebelt-domain.workspace = true
prost = "=0.14.4"
thiserror = "=2.0.20"
uuid = "=1.26.0"

[lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"
