{{/* SPDX-License-Identifier: Apache-2.0 */}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "filebelt-onlyoffice.name" . }}-default-deny
  labels:
{{ include "filebelt-onlyoffice.labels" . | indent 4 }}
  annotations:
{{ include "filebelt-onlyoffice.annotations" . | indent 4 }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
  ingress: []
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "filebelt-onlyoffice.name" . }}-ingress
  labels:
{{ include "filebelt-onlyoffice.labels" . | indent 4 }}
  annotations:
{{ include "filebelt-onlyoffice.annotations" . | indent 4 }}
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: filebelt-onlyoffice, app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: onlyoffice-adapter}
  policyTypes: [Ingress]
  ingress:
    - from:
{{ toYaml .Values.networkPolicy.oxibeltIngress.from | indent 8 }}
      ports: [{port: https, protocol: TCP}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "filebelt-onlyoffice.name" . }}-egress
  labels:
{{ include "filebelt-onlyoffice.labels" . | indent 4 }}
  annotations:
{{ include "filebelt-onlyoffice.annotations" . | indent 4 }}
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: filebelt-onlyoffice, app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: onlyoffice-adapter}
  policyTypes: [Egress]
  egress:
    - to:
{{ toYaml .Values.networkPolicy.dns.to | indent 8 }}
      ports: [{port: 53, protocol: UDP}, {port: 53, protocol: TCP}]
    - to:
{{ toYaml .Values.networkPolicy.core.to | indent 8 }}
      ports: [{port: {{ .Values.networkPolicy.core.port }}, protocol: TCP}]
    - to:
{{ toYaml .Values.networkPolicy.io.to | indent 8 }}
      ports: [{port: {{ .Values.networkPolicy.io.port }}, protocol: TCP}]
    - to:
{{ toYaml .Values.networkPolicy.egressGateway.to | indent 8 }}
      ports: [{port: {{ .Values.networkPolicy.egressGateway.port }}, protocol: TCP}]
    {{- if .Values.networkPolicy.privateEgress.enabled }}
    - to:
{{ toYaml .Values.networkPolicy.privateEgress.to | indent 8 }}
      ports: [{port: {{ .Values.networkPolicy.privateEgress.port }}, protocol: TCP}]
    {{- end }}
    {{- if .Values.networkPolicy.otlp.enabled }}
    - to:
{{ toYaml .Values.networkPolicy.otlp.to | indent 8 }}
      ports: [{port: {{ .Values.networkPolicy.otlp.port }}, protocol: TCP}]
    {{- end }}
